language: elixir
jobs:
  include:
    - elixir: 1.6.4
      otp_release: 19.0
    - elixir: 1.7.3
      otp_release: 19.0
    - elixir: 1.8.0
      otp_release: 20.0
    - elixir: 1.9.1
      otp_release: 20.0
    - elixir: 1.10.2
      otp_release: 22.0
notifications:
  recipients:
    - andrew@andrewtimberlake.com
    - herman@verschooten.net
